name: Run tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        django-version: ['~=2.1.0', '~=2.2.8', '~=3.0.0', '~=3.1.0', '~=3.2.0']
        exclude:
          - python-version: '3.8'
            django-version: '~=2.1.0'
          - python-version: '3.9'
            django-version: '~=2.1.0'
          - python-version: '3.10'
            django-version: '~=2.1.0'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip virtualenv
      - name: Run Tests
        env:
          DJANGO_VERSION: ${{ matrix.django-version }}
        run: "./dev_server.sh -d test"
